### ISSUE TITLE
something wrong when i start a project

### ISSUE THREAD

**Issue by zlydoctor** [rochacbruno/quokka_ng#3]
hi
my python version is 3.6,and i try to use  quokka for my project.
first step,i installed quokka successfully with 'pip install quokka'
then,when i use 'quokka init mywebsite',there's an error '[Errno 2] No such file or directory: 'settings.yml''.
i also can not find the file.
how can i solve it?

best regards

**Comment by zlydoctor** [comment]
bogon:quokka_ng seanliu$ quokka init mywebsite
Traceback (most recent call last):
  File "/usr/local/bin/quokka", line 7, in <module>
    from quokka.cli import main
  File "/usr/local/lib/python3.6/site-packages/quokka/cli.py", line 15, in <module>
    app = create_app()
  File "/usr/local/lib/python3.6/site-packages/quokka/__init__.py", line 33, in create_app
    app = create_app_base(test=test, **settings)
  File "/usr/local/lib/python3.6/site-packages/quokka/__init__.py", line 16, in create_app_base
    configure_dynaconf(app)
  File "/usr/local/lib/python3.6/site-packages/quokka/core/flask_dynaconf.py", line 10, in configure_dynaconf
    FlaskDynaconf(app, dynaconf_instance=settings)
  File "/usr/local/lib/python3.6/site-packages/dynaconf/contrib/flask_dynaconf.py", line 89, in __init__
    self.init_app(app, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/dynaconf/contrib/flask_dynaconf.py", line 94, in init_app
    self.settings = self.dynaconf_instance or LazySettings(**self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/dynaconf/utils/functional.py", line 207, in inner
    self._setup()
  File "/usr/local/lib/python3.6/site-packages/dynaconf/base.py", line 96, in _setup
    self._wrapped = Settings(settings_module=settings_module)
  File "/usr/local/lib/python3.6/site-packages/dynaconf/base.py", line 138, in __init__
    self.execute_loaders()
  File "/usr/local/lib/python3.6/site-packages/dynaconf/base.py", line 476, in execute_loaders
    module_loader(self, namespace=namespace)
  File "/usr/local/lib/python3.6/site-packages/dynaconf/loaders/__init__.py", line 20, in module_loader
    yaml_loader.load(obj, filename=settings_module, namespace=namespace)
  File "/usr/local/lib/python3.6/site-packages/dynaconf/loaders/yaml_loader.py", line 37, in load
    yaml_data = yaml.load(open(filename))
FileNotFoundError: [Errno 2] No such file or directory: 'settings.yml'

**Comment by rochacbruno** [comment]
Hi, I'll take a look, it should not require the `settings.yml` file as you are running `init` which is the command which will generate it.

I will try to fix this soon

**Comment by zlydoctor** [comment]
i'll use quokka for content management.Lots of featrues i should be learned after install.So could you please reply to this issue when you fixed it,thx a lot

**Comment by rochacbruno** [comment]
@zlydoctor 
https://github.com/rochacbruno/quokka_ng#setup-a-contributor-environment
