### ISSUE TITLE
Warnings in initial

### ISSUE THREAD

**Issue by heyton** [rochacbruno/quokka_ng#84]
I use command:
`quokka init NewWebsite --theme=flex --modules=gitpages,heroku`

And get this text in initial every time:

> 🎨 Warning: flex theme not installed
> 🚚 Warning: gitpages,heroku modules not installed
> 🔧 Warning: Config file not written

**Comment by rochacbruno** [comment]
hi @heyton that is expected because those 3 functionalities are not implemented yet.
#56 #55 and #49 are issues to cover that things. 

As I am working almost alone on this project it may take a while to implement :(

Contributions are also welcome!

Thanks

**Comment by heyton** [comment]
@rochacbruno 
after `quokka runserver`
i get:

> Quokka project not found, run `quokka init [projectname] [.]` to start a new project or ensure `./quokka.yml` exists. Error: [Errno 2] No such file or directory: '.secrets.yml'

Does it mean that this project not work and in deep WIP? :(

**Comment by rochacbruno** [comment]
someone reported this on IRC #49

The project is WIP the basic parts are working good I am hosting my site using this same repository

You error says you need the .secrets file which is missing, I will work to fix that issue

**Comment by heyton** [comment]
@rochacbruno 
I created file .secrets.yml and project running.
But for now I have new error:

> 04.02 16:53:06 werkzeug     INFO     127.0.0.1 - - [04/Feb/2018 16:53:06] "GET /all/ HTTP/1.1" 500 -
> 04.02 16:53:06 werkzeug     ERROR    Error on request:
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/werkzeug/serving.py", line 270, in run_wsgi
>     execute(self.server.app)
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/werkzeug/serving.py", line 258, in execute
>     application_iter = app(environ, start_response)
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
>     response = self.handle_exception(e)
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1547, in handle_exception
>     return self.finalize_request(handler(e), from_error_handler=True)
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/quokka/core/error_handlers.py", line 54, in server_error_page
>     return render_template("errors/server_error.html"), 500
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/templating.py", line 134, in render_template
>     context, ctx.app)
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/templating.py", line 116, in _render
>     rv = template.render(context)
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
>     return original_render(self, *args, **kwargs)
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
>     return self.environment.handle_exception(exc_info, True)
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
>     raise value.with_traceback(tb)
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/quokka/templates/errors/server_error.html", line 2, in top-level template code
>     {% extends theme("base.html") %}
> jinja2.exceptions.UndefinedError: 'theme' is undefined
